-- Add up migration script here

INSERT INTO courses (id, name, moa, mcr_code, crs, route, award)
VALUES
(uuid_generate_v4(), 'Mathematics MMath', 'FT', 'C038DUFHQ', 'CM1000', 'C038', 'MMATHSW'),
(uuid_generate_v4(), 'Computer Science with Artificial Intelligence with Foundation Year BSc(Hons)', 'FT', 'C041UUFHQ', 'CC1001', 'C042', 'BSCH'),
(uuid_generate_v4(), 'Computer Science with Cyber Security with Foundation Year BSc(Hons)', 'FT', 'C043DUFHQ', 'CC1001', 'C043', 'BSCHSW'),
(uuid_generate_v4(), 'Computer Science with Foundation Year BSc(Hons)', 'FT', 'C045DUFHQ', 'CC1001', 'C045', 'BSCHSW'),
(uuid_generate_v4(), 'Computer Science with Games Programming with Foundation Year BSc(Hons)', 'FT', 'C047DUFHQ', 'CC1001', 'C047', 'BSCHSW'),
(uuid_generate_v4(), 'Computing with Foundation Year BSc(Hons)', 'FT', 'C049DUFHQ', 'CC1001', 'C049', 'BSCHSW'),
(uuid_generate_v4(), 'Software Engineering with Foundation Year BSc(Hons)', 'FT', 'C051DUFHQ', 'CC1001', 'C051', 'BSCHSW'),
(uuid_generate_v4(), 'Information Technology (Top-up) BSc(Hons)', 'FT', 'C107DUFHQ', 'CC1491', 'C107', 'BSCHTOPUP'),
(uuid_generate_v4(), 'Web Programming with Cyber Security BSc(Hons)', 'FT', 'C109DUFHQ', 'CC1000', 'C101', 'BSCH'),
(uuid_generate_v4(), 'Computer Science with Cyber Security BSc(Hons)', 'FT', 'C129DUFHQ', 'CC100', 'C114', 'BAH'),
(uuid_generate_v4(), 'Applied Artificial Intelligence MSc', 'FT', 'C134DPFHQ', 'CC310', 'C134', 'MSC'),
(uuid_generate_v4(), 'Computer Science BSc(Hons)', 'FT', 'C184DUFHQ', 'CC100', 'C184', 'BSCHSWCE'),
(uuid_generate_v4(), 'Computer Science with Games Programming BSc(Hons)', 'FT', 'C186DUFHQ', 'CC100', 'C186', 'BSCHSW'),
(uuid_generate_v4(), 'Computer Science MSci', 'FT', 'C188DUFHQ', 'CC1300', 'C188', 'MSCI'),
(uuid_generate_v4(), 'Information Technology BSc(Hons)', 'FT', 'C206DUFHQ', 'CC157', 'C106', 'BAH'),
(uuid_generate_v4(), 'Cyber Security and Digital Forensics MSc', 'FT', 'C355DPFHQ', 'CC300', 'C355', 'MSC'),
(uuid_generate_v4(), 'Data Analytics MSc', 'FT', 'C364DPFHQ', 'CC310', 'C364', 'MSC'),
(uuid_generate_v4(), 'Artificial Intelligence MSc', 'FT', 'C365DPFHQ', 'CC310', 'C365', 'MSC'),
(uuid_generate_v4(), 'Computing MSc', 'FT', 'C366DPFHQ', 'CC300', 'C366', 'MSC'),
(uuid_generate_v4(), 'Mathematics BSc(Hons)', 'FT', 'C372DUFHQ', 'CM100', 'C372', 'BSCHSW'),
(uuid_generate_v4(), 'Information Systems Management MSc', 'FT', 'C404DPFHQ', 'CC310', 'C404', 'MSC'),
(uuid_generate_v4(), 'Computer Science with Artificial Intelligence BSc(Hons)', 'FT', 'C473DUFHQ', 'CC100', 'C473', 'BSCHSW'),
(uuid_generate_v4(), 'Games Development (Design) BA(Hons)', 'FT', 'C475DUFHQ', 'CC172', 'C475', 'BAHSWCE'),
(uuid_generate_v4(), 'Games Development (Production) BSc(Hons)', 'FT', 'C476DUFHQ', 'CC172', 'C476', 'BSCHSWCE'),
(uuid_generate_v4(), 'Games Development (Art) BA(Hons)', 'FT', 'C477DUFHQ', 'CC172', 'C477', 'BAHSWCE'),
(uuid_generate_v4(), 'Web Programming BSc(Hons)', 'FT', 'C520DUFHQ', 'CC1000', 'C520', 'BSCHSW'),
(uuid_generate_v4(), 'Exchange Students', 'FT', 'C700DUFHQB', 'CX700', 'C700', 'ROA'),
(uuid_generate_v4(), 'Research Exchange Students (Computer Science)', 'FT', 'C721DPFHQE', 'CX7001', 'C721', 'ROA PG'),
(uuid_generate_v4(), 'Cyber Security and Digital Forensics MSc (Royal Academy of Police) (Bahrain)', 'FT', 'C936DPFHQ', 'CX9300', 'C936', 'MSC'),
(uuid_generate_v4(), 'Computer Science and Informatics (MA by Research)', 'FT', 'CX501DPFHQ', 'CX501', 'CX501', 'MAR'),
(uuid_generate_v4(), 'Computer Science and Informatics (MSc by Research)', 'FT', 'CX502DPFHQ', 'CX502', 'CX502', 'MSCR'),
(uuid_generate_v4(), 'Computer Science and Informatics (PhD)', 'FT', 'CX505DPFHQ', 'CX505', 'CX505', 'PHD'),
(uuid_generate_v4(), 'Computing BSc(Hons)', 'FT', 'G407DUFHQ', 'CC100', 'C326', 'BSCHSWCE'),
(uuid_generate_v4(), 'Applied Computing (Top-up) BSc(Hons)', 'FT', 'G409DUFHQ', 'CC141', 'C113', 'BSCHTOPUP'),
(uuid_generate_v4(), 'Computing in Business BA(Hons)', 'FT', 'G423DUFHQ', 'CC150', 'C100', 'BAHSWCE'),
(uuid_generate_v4(), 'Software Engineering BSc(Hons)', 'FT', 'G600DUFHQ', 'CC156', 'C347', 'BSCHSW'),
(uuid_generate_v4(), 'Software Engineering MEng', 'FT', 'G601DUFHQ', 'CC1300', 'C311', 'MENGSW'),
(uuid_generate_v4(), 'Electronic Engineering and Computer Systems BEng(Hons)', 'FT', 'GH46DUFHQ1', 'NE1001', 'N113', 'BENGHSW'),
(uuid_generate_v4(), 'Engineering Foundation Year', 'FT', 'H108DUFHQ', 'NX100', 'N147', 'BENGHSW'),
(uuid_generate_v4(), 'Mechanical Engineering (Top-up) BEng(Hons)', 'FT', 'H302DDUFHQ', 'NM140', 'N141', 'BENGHTOPUP'),
(uuid_generate_v4(), 'Mechanical Engineering MEng', 'FT', 'H303DUFHQ', 'NM1000', 'N407', 'MENGSW'),
(uuid_generate_v4(), 'Automotive and Motorsport Engineering MEng', 'FT', 'H332DUFHQ', 'NM1000', 'N103', 'MENG'),
(uuid_generate_v4(), 'Electronic and Electrical Engineering BEng(Hons)', 'FT', 'H600DUFHQ1', 'NE1001', 'N112', 'BENGH'),
(uuid_generate_v4(), 'Electronic Engineering (Top-up) BEng(Hons)', 'FT', 'H603DUFHQ', 'NE140', 'N142', 'BENGHTOPUP'),
(uuid_generate_v4(), 'Electronic and Communication Engineering (Top-up) BEng(Hons)', 'FT', 'H604DUFHQ', 'NE140', 'N143', 'BENGHTOPUP'),
(uuid_generate_v4(), 'Electronic Engineering BEng(Hons)', 'FT', 'H610DUFHQ1', 'NE1001', 'N153', 'BENGHSW'),
(uuid_generate_v4(), 'Electronic and Electrical Engineering MEng', 'FT', 'H611DUFHQ', 'NE1000', 'N101', 'MENG20-SW'),
(uuid_generate_v4(), 'Electronic Engineering MEng', 'FT', 'H612DUFHQ', 'NE1000', 'N400', 'MENGSW'),
(uuid_generate_v4(), 'Electronic and Communication Engineering BEng(Hons)', 'FT', 'H640DUFHQ1', 'NE1001', 'N154', 'BENGHSW'),
(uuid_generate_v4(), 'Computer Systems Engineering BEng(Hons)', 'FT', 'H6G4DUFHQ1', 'NE1001', 'N122', 'BENGHSW'),
(uuid_generate_v4(), 'Computing MComp', 'FT', 'I102DUFHQ', 'CC1300', 'C143', 'MCOMPSW'),
(uuid_generate_v4(), 'Sound Engineering and Audio Technology BSc(Hons)', 'FT', 'N001DUFHQ', 'NE112', 'N001', 'BSCHSW'),
(uuid_generate_v4(), 'Mechanical Engineering (Top-up) BEng(Hons) (ALBA)', 'FT', 'N003DUFHQ', 'NX9140', 'N003', 'BENGHTOPUP'),
(uuid_generate_v4(), 'Automotive and Motorsport Engineering with Foundation Year BEng(Hons)', 'FT', 'N004DUFHQ', 'NM1002', 'N004', 'BENGHSW'),
(uuid_generate_v4(), 'Mechanical Engineering with Foundation Year BEng(Hons)', 'FT', 'N006DUFHQ', 'NM1002', 'N006', 'BENGHSW'),
(uuid_generate_v4(), 'Mechatronic Engineering with Foundation Year BEng(Hons)', 'FT', 'N008DUFHQ', 'NM1002', 'N008', 'BENGHSW'),
(uuid_generate_v4(), 'Civil Engineering with Foundation Year BEng(Hons)', 'FT', 'N010DUFHQ', 'NM1002', 'N010', 'BENGHSW'),
(uuid_generate_v4(), 'Electronic and Communication Engineering with Foundation Year BEng(Hons)', 'FT', 'N012DUFHQ', 'NM1002', 'N012', 'BENGHSW'),
(uuid_generate_v4(), 'Electronic and Electrical Engineering with Foundation Year BEng(Hons)', 'FT', 'N014DUFHQ', 'NM1002', 'N014', 'BENGHSW'),
(uuid_generate_v4(), 'Electronic Engineering and Computer Systems with Foundation Year BEng(Hons)', 'FT', 'N016DUFHQ', 'NM1002', 'N016', 'BENGHSW'),
(uuid_generate_v4(), 'Electrical and Electronic Engineering with Control Systems (Top-up) BEng(Hons) (ALBA)', 'FT', 'N018DUFHQ', 'NX9140', 'N018', 'BENGHTOPUP'),
(uuid_generate_v4(), 'Foundation Engineering BEng(Hons) (FNU)', 'FT', 'N040DUFHQ', 'NX9100', 'N040', 'BENGH'),
(uuid_generate_v4(), 'Civil Engineering BEng(Hons)', 'FT', 'N104DUFHQ', 'NC100', 'N104', 'BENGHSW'),
(uuid_generate_v4(), 'Civil Engineering MEng', 'FT', 'N107DUFHQ', 'NC1001', 'N107', 'MENG20-SW'),
(uuid_generate_v4(), 'Mechanical Engineering BEng(Hons)', 'FT', 'N115DUFHQ', 'NM1001', 'N115', 'BENGHSW'),
(uuid_generate_v4(), 'Energy Engineering BEng(Hons)', 'FT', 'N118DUFHQ', 'NM1001', 'N118', 'BENGHSW'),
(uuid_generate_v4(), 'Automotive Engineering MSc', 'FT', 'N272DPFHQ', 'NM320', 'N272', 'MSC'),
(uuid_generate_v4(), 'Electronic and Communication Engineering MSc', 'FT', 'N276DPFHQ', 'NE301', 'N276', 'MSC'),
(uuid_generate_v4(), 'Mechanical Engineering MSc', 'FT', 'N311DPFHQ', 'NM330', 'N311', 'MSC'),
(uuid_generate_v4(), 'Engineering Management MSc', 'FT', 'N314DPFHQ', 'NM340', 'N314', 'MSC'),
(uuid_generate_v4(), 'Engineering Control Systems and Instrumentation MSc', 'FT', 'N315DPFHQ', 'NE300', 'N315', 'MSC'),
(uuid_generate_v4(), 'Oil and Gas Engineering MSc', 'FT', 'N353DPFHQ', 'NM350', 'N353', 'MSC'),
(uuid_generate_v4(), 'Mechatronic Engineering BEng(Hons)', 'FT', 'N364DUFHQ', 'NM1001', 'N364', 'BENGHSW'),
(uuid_generate_v4(), 'Engineering Design BEng(Hons)', 'FT', 'N365DUFHQ', 'NM1001', 'N365', 'BENGHSW'),
(uuid_generate_v4(), 'Electronic Engineering MSc', 'FT', 'N370DPFHQ', 'NE3005', 'N370', 'MSC'),
(uuid_generate_v4(), 'Electronic and Automotive Engineering MSc', 'FT', 'N371DPFHQ', 'NE3006', 'N371', 'MSC'),
(uuid_generate_v4(), 'Automotive and Motorsport Engineering BEng(Hons)', 'FT', 'N419DUFHQ', 'NM1001', 'N419', 'BENGHSW'),
(uuid_generate_v4(), 'Mechatronic Engineering MEng', 'FT', 'N464DUFHQ', 'NM1000', 'N464', 'MENGSW'),
(uuid_generate_v4(), 'Sound Engineering and Music Production BSc(Hons)', 'FT', 'N476DUFHQ', 'NE112', 'N476', 'BSCHSW'),
(uuid_generate_v4(), 'Electronic Engineering and Computer Systems BEng(Hons) (FNU)', 'FT', 'N613DUFHQ', 'NX9150', 'N613', 'BENGH'),
(uuid_generate_v4(), 'Research Exchange Students (Engineering)', 'FT', 'N715DPFHQE', 'NX7001', 'N715', 'ROA PG'),
(uuid_generate_v4(), 'Electronic and Communication Engineering (FNU) BEng(Hons)', 'FT', 'N940DUFHQ', 'NX9150', 'N940', 'BENGH'),
(uuid_generate_v4(), 'Mechanical Engineering (MA by Research)', 'FT', 'NX501DPFHQ', 'NX501', 'NX501', 'MAR'),
(uuid_generate_v4(), 'Engineering (MSc by Research)', 'FT', 'NX502DPFHQ', 'NX502', 'NX502', 'MSCR'),
(uuid_generate_v4(), 'Mechanical Engineering (MPhil)', 'FT', 'NX503DPFHQ', 'NX503', 'NX503', 'MPHIL'),
(uuid_generate_v4(), 'Engineering (PhD)', 'FT', 'NX505DPFHQ', 'NX505', 'NX505', 'PHD'),
(uuid_generate_v4(), 'Electronic/Electrical Engineering (MA by Research)', 'FT', 'NX508DPFHQ', 'NX501', 'NX508', 'MAR'),
(uuid_generate_v4(), 'Electronic/Electrical Engineering (MSc by Research)', 'FT', 'NX509DPFHQ', 'NX502', 'NX509', 'MSCR'),
(uuid_generate_v4(), 'Physics (PhD)', 'FT', 'NX510DPFHQ', 'NX5000', 'NX510', 'PHD'),
(uuid_generate_v4(), 'Music Technology (MSc by Research)', 'FT', 'NX511DPFHQ', 'NX502', 'NX511', 'MSCR'),
(uuid_generate_v4(), 'Physics (MSc by Research)', 'FT', 'NX512DPFHQ', 'NX5001', 'NX512', 'MSCR'),
(uuid_generate_v4(), 'Electronic/Electrical Engineering (PhD)', 'FT', 'NX513DPFHQ', 'NX505', 'NX513', 'PHD'),
(uuid_generate_v4(), 'Music Technology (MPhil)', 'FT', 'NX514DPFHQ', 'NX503', 'NX514', 'MPHIL'),
(uuid_generate_v4(), 'Music Technology (PhD)', 'FT', 'NX515DPFHQ', 'NX505', 'NX515', 'PHD'),
(uuid_generate_v4(), 'Electronic/Electrical Engineering (MPhil)', 'FT', 'NX520DPFHQ', 'NX503', 'NX520', 'MPHIL'),
(uuid_generate_v4(), 'Music Technology (MA by Research)', 'FT', 'NX521DPFHQ', 'NX501', 'NX521', 'MAR'),
(uuid_generate_v4(), 'Civil Engineering (PhD)', 'FT', 'NX522DPFHQ', 'NX505', 'NX522', 'PHD'),
(uuid_generate_v4(), 'Civil Engineering (MSc by Research)', 'FT', 'NX524DPFHQ', 'NX502', 'NX524', 'MSCR'),
(uuid_generate_v4(), 'PhD by Publication', 'FT', 'NX596DPFHQ', 'NX599', 'NX596', 'PHDPUB'),
(uuid_generate_v4(), 'Data Science (Distance Learning) PBA Sept FT', 'FT DL', 'C054DUFDL', 'CC1002', 'C054', 'ROA'),
(uuid_generate_v4(), 'Data Science (Distance Learning) PBA Jan FT', 'FT DL', 'C055DUFDL', 'CC1002', 'C055', 'ROA'),
(uuid_generate_v4(), 'Data Science (Distance Learning) BSc(Hons)', 'FT DL', 'C057DUFDL', 'CC1004', 'C057', 'BSCH'),
(uuid_generate_v4(), 'Computer Science and Informatics (MSc by Research) (Distance Learning)', 'FT DL', 'CX502DPFDL', 'XX5002', 'CX502', 'MSCR'),
(uuid_generate_v4(), 'Computer Science and Informatics (PhD) (Distance Learning)', 'FT DL', 'CX505DPFDL', 'XX5001', 'CX505', 'PHD'),
(uuid_generate_v4(), 'Mechanical Engineering (MSc by Research) (Distance Learning)', 'FT DL', 'NX502DPFDL', 'XX5002', 'NX502', 'MSCR'),
(uuid_generate_v4(), 'Mechanical Engineering (PhD) (Distance Learning)', 'FT DL', 'NX505DPFDL', 'XX5001', 'NX505', 'PHD'),
(uuid_generate_v4(), 'Electronic/Electrical Engineering (MSc by Research) (Distance Learning)', 'FT DL', 'NX509DPFDL', 'XX5002', 'NX509', 'MSCR'),
(uuid_generate_v4(), 'Physics (PhD) (Distance Learning)', 'FT DL', 'NX510DPFDL', 'XX5001', 'NX510', 'PHD'),
(uuid_generate_v4(), 'Music Technology (MSc by Research) (Distance Learning)', 'FT DL', 'NX511DPFDL', 'XX5002', 'NX511', 'MSCR'),
(uuid_generate_v4(), 'Music Technology (MA by Research) (Distance Learning)', 'FT DL', 'NX521DPFDL', 'XX5002', 'NX521', 'MAR'),
(uuid_generate_v4(), 'Civil Engineering (PhD) (Distance Learning)', 'FT DL', 'NX522DPFDL', 'XX5001', 'NX522', 'PHD'),
(uuid_generate_v4(), 'Civil Engineering (MSc by Research) (Distance Learning)', 'FT DL', 'NX524DPFDL', 'XX5002', 'NX524', 'MSCR'),
(uuid_generate_v4(), 'PhD by Publication (Distance Learning)', 'FT DL', 'NX596DPFDL', 'XX5007', 'NX596', 'PHDPUB'),
(uuid_generate_v4(), 'Associate students Undergraduate', 'PT', 'C290DUPHQ', 'CX290', 'C290', 'ROA'),
(uuid_generate_v4(), 'Associate students Postgraduate', 'PT', 'C295DPPHQ', 'CX290', 'C295', 'ROA'),
(uuid_generate_v4(), 'Informatics (MPhil)', 'PT', 'CX553DPPHQ', 'CX553', 'CX553', 'MPHIL'),
(uuid_generate_v4(), 'Doctor of Letters', 'PT', 'CX558DPPHQ', 'CX5500', 'CX558', 'DLITT'),
(uuid_generate_v4(), 'Doctor of Science', 'PT', 'CX562DPPHQ', 'CX5500', 'CX562', 'DSC'),
(uuid_generate_v4(), 'Data Science (Distance Learning) PBA PT', 'PT DL', 'C056DUPDL', 'CC1003', 'C056', 'ROA'),
(uuid_generate_v4(), 'Applied Artificial Intelligence MSc (Distance Learning)', 'PT DL', 'C134DPPDL', 'CC8100', 'C134', 'MSC'),
(uuid_generate_v4(), 'Applied Artificial Intelligence MSc (Distance Learning) (3 years)', 'PT DL', 'C134DPPDL1', 'CC8000', 'C134', 'MSC'),
(uuid_generate_v4(), 'Data Analytics MSc (Distance Learning)', 'PT DL', 'C804DPPHQ', 'CC8000', 'C804', 'MSC'),
(uuid_generate_v4(), 'Artificial Intelligence MSc (Distance Learning)', 'PT DL', 'C805DPPHQ', 'CC8000', 'C805', 'MSC'),
(uuid_generate_v4(), 'Cyber Security and Digital Forensics MSc (Distance Learning) (2 years)', 'PT DL', 'C815DPPHQ', 'CC8300', 'C815', 'MSC'),
(uuid_generate_v4(), 'Cyber Security and Digital Forensics MSc (Distance Learning) (3 years)', 'PT DL', 'C815DPPHQ1', 'CC8200', 'C815', 'MSC'),
(uuid_generate_v4(), 'Engineering Management MSc (Distance Learning)', 'PT DL', 'N337DPPDL', 'NM403', 'N337', 'MSC'),
(uuid_generate_v4(), 'Engineering Management PgDip (Distance Learning)', 'PT DL', 'N338DPPDL', 'NM404', 'N338', 'PGDIP'),
(uuid_generate_v4(), 'Engineering Management PgCert (Distance Learning)', 'PT DL', 'N339DPPDL', 'NM405', 'N339', 'PGCERT'),
(uuid_generate_v4(), 'Mechanical Engineering (PhD by Publication) (Distance Learning)', 'PT DL', 'NX399DPPDL', 'XX5004', 'NX399', 'PHDPUB'),
(uuid_generate_v4(), 'Electronic/Electrical Engineering (PhD) (Distance Learning)', 'PT DL', 'NX573DPFDL', 'XX5004', 'NX573', 'PHD');
